# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/coworking.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'protos/coworking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/coworking.proto\"#\n\x0b\x42ookRequest\x12\x14\n\x0cworkplace_id\x18\x01 \x01(\x05\"0\n\x0c\x42ookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2@\n\x10\x43oworkingService\x12,\n\rBookWorkplace\x12\x0c.BookRequest\x1a\r.BookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.coworking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=26
  _globals['_BOOKREQUEST']._serialized_end=61
  _globals['_BOOKRESPONSE']._serialized_start=63
  _globals['_BOOKRESPONSE']._serialized_end=111
  _globals['_COWORKINGSERVICE']._serialized_start=113
  _globals['_COWORKINGSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
